import Head from "next/head";
import Link from "next/link"

// Components
import { Card } from "../components/Card";

export default function Home() {
  return (
    <div className="container pt-5">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container d-flex justify-content-center">
        <Card />
      </div>
    </div>
  );
}
